version: "3.7"
services:
  app-client:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: api-back-client
    container_name: api-back-client
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - back-end

  nginx:
    image: nginx:alpine
    container_name: back-client-nginx
    restart: unless-stopped
    ports:
      - 8006:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - back-end


  db_client:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: lifefit
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepassword
    ports:
      - "3308:3306"
    volumes:
      - db_data_client:/var/lib/mysql
    networks:
      - back-end

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db_client
      MYSQL_ROOT_PASSWORD: lifefit
    networks:
      - back-end
    

networks:
  back-end:
    driver: bridge

volumes:
  db_data_client:    
