name: "deploy para a vps"

on:
 push:
   branches:
     - master
jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "entrando no repositorio puxando as alteração e subindo os docker"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.IP_DEPLOY}}
          username: "root"
          key: ${{secrets.SSH_PRIVATE_TEST}}
          passphrase: ${{ secrets.SSH_SENHA }}
          script: |
            cd ../home/ubuntu/Sistema-Academia-Back-end
            git checkout master
            git pull
