name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Adms:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: lifefit
          MYSQL_DATABASE: db_adms
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install dependencies
        run: |
          cd Adms
          composer install || composer update

      - name: Set up .env file
        run: |
          cd Adms
          cp .env.example .env
          php artisan key:generate

      - name: Run tests
        run: |
          cd Adms
          php artisan migrate --env=testing
          php artisan test

  Client:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: lifefit
          MYSQL_DATABASE: db_client
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install dependencies
        run: |
          cd Client
          composer install || composer update

      - name: Set up .env file
        run: |
          cd Client
          cp .env.example .env
          php artisan key:generate

      - name: Run tests
        run: |
          cd Client
          php artisan migrate --env=testing
          php artisan test
